#cloud-config

hostname: HostName

coreos:
  units:
    - name: ipxe-installd.service
      command: start
      content: |
        [Unit]
        Description=ipxe-installd
        After=network-online.target download-cloud-config.service
        Requires=network-online.target download-cloud-config.service 
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/coreos-install -d /dev/sda -c /root/InstallationKind-coreos-cloud-config.yml -b http://iPXE_Server_IP/images/coreos/amd64-usr -V CoreOSInstallationVersion

    - name: download-cloud-config.service
      command: start
      content: |
        [Unit]
        Requires=network-online.target
        After=network-online.target
        Description=download-cloud-config.service
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/wget http://iPXE_Server_IP/cloud-configs/InstallationKind-coreos-cloud-config.yml -O /root/InstallationKind-coreos-cloud-config.yml

    - name: ipxe-cleand.service
      command: start
      content: |
        [Unit]
        Description=pxe-cleand
        Requires=network-online.target ipxe-installd.service
        After=network-online.target ipxe-installd.service
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/bin/bash -c 'wget -O - http://iPXE_Server_IP/bin/ipxe-cleand.sh | bash -'
