#cloud-config

hostname: InstallationHostname

coreos:
  units:
    - name: ipxe-installd.service
      command: start
      content: |
        [Unit]
        Description=ipxe-installd
        After=network-online.target
        Requires=network-online.target
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStartPre=/usr/bin/wget http://iPXE_Server_IP/cloud-configs/coreos_stage/InstallationHostname-coreos-cloud-config.yml -O /root/InstallationHostname-coreos-cloud-config.yml
        ExecStart=/bin/bash -c "/usr/bin/coreos-install -d /dev/`ls /sys/block/ | grep -E '(s|v)da'` -c /root/InstallationHostname-coreos-cloud-config.yml -b http://iPXE_Server_IP/images/coreos/amd64-usr -V CoreOSInstallationVersion"
        ExecStartPost=/bin/bash -c 'wget -O - http://iPXE_Server_IP/bin/ipxe-cleand.sh | bash -'

users:
  - name: core
    passwd: $6$/neOHTHIzw0y0$dbIFeLluwRKKZ0mrAvLSczcmJ3B3FxE1AD864XUF9GcKmG3YwtXMb2aukEQgSaoIuEuO3zWV7uMtzqkvx43Iz1
